export const Timezones = [
  {"value": 0,"name":"Universal Coordinated Time (UTC/GMT)"},
  {"value": 1,"name":"European Central Time (ECT/GMT+1:00)"},
  {"value": 2,"name":"Eastern European Time (EET/GMT+2:00)"},
  {"value": 2,"name":"(Arabic) Egypt Standard Time (ART/GMT+2:00)"},
  {"value": 3,"name":"Eastern African Time (EAT/GMT+3:00)"},
  {"value": 3.5,"name":"Middle East Time (MET/GMT+3:30)"},
  {"value": 4,"name":"Near East Time (NET/GMT+4:00)"},
  {"value": 5,"name":"Pakistan Lahore Time (PLT/GMT+5:00)"},
  {"value": 5.5,"name":"India Standard Time (IST/GMT+5:30)"},
  {"value": 6,"name":"Bangladesh Standard Time (BST/GMT+6:00)"},
  {"value": 7,"name":"Vietnam Standard Time (VST/GMT+7:00)"},
  {"value": 8,"name":"China Taiwan Time (CTT/GMT+8:00)"},
  {"value": 9,"name":"Japan Standard Time (JST/GMT+9:00)"},
  {"value": 9.5,"name":"Australia Central Time (ACT/GMT+9:30)"},
  {"value": 10,"name":"Australia Eastern Time (AET/GMT+10:00)"},
  {"value": 11,"name":"Solomon Standard Time (SST/GMT+11:00)"},
  {"value": 12,"name":"New Zealand Standard Time (NST/GMT+12:00)"},
  {"value": -11,"name":"	Midway Islands Time (MIT/GMT-11:00)"},
  {"value": -10,"name":"Hawaii Standard Time (HST/GMT-10:00)"},
  {"value": -9,"name":"Alaska Standard Time (AST/GMT-9:00)"},
  {"value": -8,"name":"Pacific Standard Time (PST/GMT-8:00)"},
  {"value": -7,"name":"Phoenix Standard Time (PNT/GMT-7:00)"},
  {"value": -7,"name":"Mountain Standard Time (MST/GMT-7:00)"},
  {"value": -6,"name":"Central Standard Time (CST/GMT-6:00)"},
  {"value": -5,"name":"Eastern Standard Time (EST/GMT-5:00)"},
  {"value": -5,"name":"Indiana Eastern Standard Time (IET/GMT-5:00)"},
  {"value": -4,"name":"Puerto Rico and US Virgin Islands Time (PRT/GMT-4:00)"},
  {"value": -3,"name":"Canada Newfoundland Time (CNT/GMT-3:30)"},
  {"value": -3,"name":"Argentina Standard Time (AGT/GMT-3:00)"},
  {"value": -3,"name":"Brazil Eastern Time (BET/GMT-3:00)"},
  {"value": -1,"name":"Central African Time (CAT/GMT-1:00)"}
];
